services:
  app:
    build: .
    container_name: spotify-api
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
      - redis
    networks:
      - spotify-net

  db:
    image: mysql:8.0
    container_name: spotify-db
    restart: always
    environment:
      MYSQL_DATABASE: backend_spotify
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - spotify-net

  redis:
    image: redis:alpine
    container_name: spotify-redis
    networks:
      - spotify-net

networks:
  spotify-net:
    driver: bridge
